version: '3' 
services:
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: always 
        volumes:  
            - ./src:/var/www/html
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - php-fpm
        ports: 
            - "80:80/tcp"
            - "443:443/tcp"
    php-fpm:
        image: bincent/php:8.0-fpm-alpine
        container_name: php-fpm
        restart: always 
        volumes:  
            - ./src:/var/www/html
        ports:  
            - "9000:9000/tcp"