version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    volumes:
      - ../:/var/www/html  # 根据自己的项目路径修改
      - ./conf.d:/etc/nginx/conf.d
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - php-fpm
    links:
      - php-fpm
    ports:
      - 80:80/tcp
      - 443:443/tcp
    network_mode: bridge

  php-fpm:
    image: bincent/php:fpm-alpine
    container_name: php-fpm
    restart: always
    volumes:
      - ../:/var/www/html # 根据自己的项目路径修改
    network_mode: bridge
